SEO task
vtex-apps/admin-pages pull request #414
Opened 2021-12-14 08:56 UTC by christianAcctGlobal

#### What problem is this solving?

#### How should this be manually tested?

[Workspace](https://seotask2--powerplanet.myvtex.com/admin/cms/store)

#### Screenshots or example usage
![image](https://user-images.githubusercontent.com/84771232/145964653-a6bfa123-668b-4920-b799-f2388435a0e9.png)

#### Type of changes

| ✔️  | Type of Change                                                                            |
| --- | ----------------------------------------------------------------------------------------- |
| \_  | Bug fix                                |
| \_  | New feature                        |
| ✔️  | Breaking change  |
| \_  | Technical improvements  |

#### Notes
Some settings may take time to be reflected in the store

#### How does this PR make you feel? [:link:](http://giphy.com/categories/emotions/)

![](https://media.giphy.com/media/TLulTJKuyLgMU/giphy.gif)

2022-01-14 19:45 UTC, camilavcoutinho requested changes

2022-01-14 19:45 UTC, camilavcoutinho commented on messages/bg.json
> +  "admin/store.advancedSettings.canonicalWithoutUrlParams.description": "Премахнете параметъра на картата от каноничния URL адрес. Може да причини проблеми, когато отидете на страница с избрани аспек
```suggestion
  "admin/store.advancedSettings.canonicalWithoutUrlParams.title": "Редовен URL адрес без URL параметри",
  "admin/store.advancedSettings.canonicalWithoutUrlParams.description": "Премахнете параметъра на картата от редовния URL адрес. Може да причини проблеми, когато отидете на страница с избрани аспекти. Тествайте внимателно, след като го включите",
```

2022-01-14 19:45 UTC, camilavcoutinho commented on messages/es.json
> +  "admin/store.advancedSettings.enablePageNumberTitle.title": "Habilitar el número de página en el meta title",
```suggestion
  "admin/store.twitterCard.description": "Por favor, elija el tipo de Twitter Card",
  "admin/store.advancedSettings.enablePageNumberTitle.title": "Activar el número de página en el metatítulo",
```

2022-01-14 19:45 UTC, camilavcoutinho commented on messages/es.json
> +  "admin/store.advancedSettings.canonicalWithoutUrlParams.description": "Elimina el parámetro de mapa de la URL canónica. Puede causar problemas al acceder a una página con facetas seleccionadas. Pru
```suggestion
  "admin/store.advancedSettings.canonicalWithoutUrlParams.description": "Elimina el parámetro de mapa de la URL canónica. Puede causar problemas al acceder a una página con facetas seleccionadas. Prueba con precaución después de la activación.",
```

2022-01-14 19:45 UTC, camilavcoutinho commented on messages/fr.json
> +  "admin/store.advancedSettings.enablePageNumberTitle.title": "Activer le numéro de page dans le meta title",
```suggestion
  "admin/store.advancedSettings.enablePageNumberTitle.title": "Activer le numéro de page dans la balise meta title",
```

2022-01-14 19:45 UTC, camilavcoutinho commented on messages/fr.json
> +  "admin/store.advancedSettings.canonicalWithoutUrlParams.description": "Supprimer le paramètre de carte de l'URL canonique. Peut causer des problèmes lors de l'accès à une page avec des facettes sél
```suggestion
  "admin/store.advancedSettings.canonicalWithoutUrlParams.description": "Supprimer le paramètre de carte de l’URL canonique. Peut causer des problèmes lors de l’accès à une page avec des facettes sélectionnées. À tester avec précaution après l’avoir activé",
```

2022-01-14 19:45 UTC, camilavcoutinho commented on messages/fr.json
> +  "admin/store.advancedSettings.removeStoreNameTitle.description": "Supprimer le nom du magasin à la fin des méta-titres des produits et des catégories"
```suggestion
  "admin/store.advancedSettings.removeStoreNameTitle.description": "Supprimer le nom du magasin à la fin des balises meta title des produits et des catégories"
```

2022-01-14 19:45 UTC, camilavcoutinho commented on messages/it.json
> +  "admin/store.advancedSettings.canonicalWithoutUrlParams.description": "Rimuovi il parametro della mappa dall'URL canonico. Può causare problemi quando si accede a una pagina con i facet selezionati
```suggestion
  "admin/store.advancedSettings.canonicalWithoutUrlParams.description": "Rimuovi il parametro della mappa dall'URL canonico. Può causare problemi quando si accede a una pagina con i facet selezionati. Testalo con cautela dopo averlo abilitato.",
```

2022-01-14 19:45 UTC, camilavcoutinho commented on messages/it.json
> +  "admin/store.advancedSettings.removeStoreNameTitle.description": "Rimuovi il nome del negozio alla fine dei meta titoli del prodotto e della categoria"
```suggestion
  "admin/store.advancedSettings.removeStoreNameTitle.description": "Rimuovi il nome del negozio alla fine dei meta title di Prodotto e Categoria"
```

2022-01-14 19:45 UTC, camilavcoutinho commented on messages/pt.json
> +  "admin/store.advancedSettings.canonicalWithoutUrlParams.description": "Remova o parâmetro do mapa do URL canônico. Pode causar problemas ao acessar uma página com facetas selecionadas. Teste com cu
```suggestion
  "admin/store.advancedSettings.canonicalWithoutUrlParams.title": "URL canônico sem parâmetros de URL",
  "admin/store.advancedSettings.canonicalWithoutUrlParams.description": "Remova o parâmetro do mapa do URL canônico. Pode causar problemas ao acessar uma página com facetas selecionadas. Teste com cuidado depois de ativá-lo",
```

2022-01-14 19:45 UTC, camilavcoutinho commented on messages/pt.json
> +  "admin/store.advancedSettings.removeStoreNameTitle.description": "Remova o nome da loja no final dos metatítulos de produto e categoria"
```suggestion
  "admin/store.advancedSettings.removeStoreNameTitle.description": "Remova o nome da loja no final dos meta títulos Produto e Categoria"
```

2022-01-14 19:45 UTC, camilavcoutinho commented on messages/ro.json
> +  "admin/store.advancedSettings.enablePageNumberTitle.description": "Adăugați un #{Număr} la sfârșitul titlului pentru a evita problema de duplicare a titlului",
```suggestion
  "admin/store.advancedSettings.enablePageNumberTitle.title": "Activează numărul de pagină în titlul meta",
  "admin/store.advancedSettings.enablePageNumberTitle.description": "Adaugă un #{Număr} la sfârșitul titlului pentru a evita problema de duplicare a titlului",
```

2022-01-14 19:45 UTC, camilavcoutinho commented on messages/ro.json
> +  "admin/store.advancedSettings.removeStoreNameTitle.description": "Eliminați numele magazinului la sfârșitul metatitlurilor de produse și categorii"
```suggestion
  "admin/store.advancedSettings.canonicalWithoutUrlParams.description": "Elimină parametrul hărții din adresa URL canonică. Este posibil să cauzeze probleme atunci când accesezi o pagină cu fațete selectate. Testează cu precauție după ce îl pornești",
  "admin/store.advancedSettings.removeStoreNameTitle.title": "Elimină numele magazinului din titlu",
  "admin/store.advancedSettings.removeStoreNameTitle.description": "Elimină numele magazinului de la finalul metatitlurilor de produse și categorii"
```

2022-01-14 19:45 UTC, camilavcoutinho commented on messages/ja.json
> +  "admin/store.advancedSettings.enablePageNumberTitle.description": "タイトルの重複の問題を回避するために、タイトルの最後に＃{番号}を追加します",
```suggestion
  "admin/store.advancedSettings.enablePageNumberTitle.description": "重複の問題を回避するために、タイトルの最後に#{番号} を追加します",
```

2022-01-14 19:45 UTC, camilavcoutinho commented on messages/ja.json
> +  "admin/store.advancedSettings.canonicalWithoutUrlParams.description": "正規URLからマップパラメータを削除します。ファセットが選択されているページに移動すると、問題が発生する可能性があります。電源を入れた後は注意してテストしてください",
```suggestion
  "admin/store.advancedSettings.canonicalWithoutUrlParams.description": "正規URLからマップパラメータを削除します。ファセットが選択されているページに移動すると、問題が発生する可能性があります。有効にしてからは注意してテストしてください",
```

2022-01-14 19:45 UTC, camilavcoutinho commented on messages/ko.json
> +  "admin/store.advancedSettings.removeStoreNameTitle.description": "제품 및 카테고리 메타 제목 끝에 있는 상점 이름 제거"
```suggestion
  "admin/store.advancedSettings.canonicalWithoutUrlParams.description": "표준 URL에서 지도 매개변수를 제거합니다. 패싯이 선택된 페이지로 이동할 때 문제가 발생할 수 있습니다. 설정 후 주의해서 테스트하십시오.",
  "admin/store.advancedSettings.removeStoreNameTitle.title": "제목에서 스토어 이름 제거",
  "admin/store.advancedSettings.removeStoreNameTitle.description": "제품 및 카테고리 메타 제목 끝에 있는 스토어 이름 제거"
```

2022-01-17 07:51 UTC, christianAcctGlobal commented on messages/es.json
> +  "admin/store.advancedSettings.enablePageNumberTitle.title": "Habilitar el número de página en el meta title",
done

2022-01-17 11:54 UTC, camilavcoutinho approved these changes

2022-01-17 12:04 UTC, sheilagomes approved these changes
LGTM

2022-02-23 13:11 UTC, merged